CREATE SCHEMA basededatos;

USE basededatos;

CREATE TABLE USUARIOS
(
ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(60) NOT NULL,
APELLIDO VARCHAR(60) NOT NULL, -- No admite valores nulos y 60 caracteres
EMAIL VARCHAR(100) NOT NULL,
USER_PASSWORD VARCHAR(25) NOT NULL,  -- ¿Es legal esto?
FOTO_PERFIL VARCHAR(25),
FECHA TIMESTAMP,
DESCRIPCION VARCHAR(1000),
NUMBER_CAMPO INT 

);

CREATE TABLE POSTEOS 
(
ID_POST INT PRIMARY KEY AUTO_INCREMENT,
IMAGEN VARCHAR(90) NOT NULL,
FECHA_REGISTRO TIMESTAMP NOT NULL, -- Fecha de creacion, formato de hora
ID_USUARIO_CREO INT NOT NULL, -- Dejar registrado que usuario creó el post
PRICE_SOL INT NOT NULL, -- Le ponemos precio al nft 
CONSTRAINT FK1_POSTEOS FOREIGN KEY(ID_USUARIO_CREO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE NO ACTION ON UPDATE NO ACTION
);


CREATE TABLE COMENTARIOS
(
ID_COMENTARIOS INT PRIMARY KEY AUTO_INCREMENT,
TEXT_COMENTARIO VARCHAR(1000) NOT NULL,
FECHA_CREACION DATE NOT NULL, -- Fecha de creacion, formato de hora
ID_POST INT NOT NULL,
ID_USUARIO INT NOT NULL,

CONSTRAINT FK1_COMENTARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT FK2_COMENTARIOS FOREIGN KEY (ID_POST) REFERENCES POSTEOS(ID_POST) ON DELETE NO ACTION ON UPDATE NO ACTION,
);
